kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edgegovernor-admin0
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:node:cloud
    #name: system:node:k8s4-master
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
